---

image: docker:latest

stages:
  - build
  - release


# login to private gitlab registry
before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY


# ==========================
#      Job templates
# ==========================
# special gitlab yaml feature, see: https://docs.gitlab.com/ce/ci/yaml/README.html#anchors

.build_php_template: &build_php_definition
  stage: build
  script:
    - docker build -t $CONTAINER_IMAGE_NAME .
    - docker push $CONTAINER_IMAGE_NAME
  only:
    - master
    - feature/migrateToAlpineLinux

.release_docker_image_template: &release_docker_image_definition
  stage: release
  script:
    - docker pull $CONTAINER_IMAGE_NAME
    - docker tag $CONTAINER_IMAGE_NAME $CONTAINER_IMAGE_RELEASE_NAME
    - docker push $CONTAINER_IMAGE_RELEASE_NAME
  only:
    - master
    - feature/migrateToAlpineLinux

# ===================
#        BUILD
# ===================

build_spryker_base_image:
  <<: *build_php_definition
  variables:
    CONTAINER_IMAGE_NAME: $CI_REGISTRY/$CI_PROJECT_PATH:${CI_BUILD_REF}-alpine


# ===================
#      RELEASE
# ===================

release_spryker_base_image:
  <<: *release_docker_image_definition
  variables:
    CONTAINER_IMAGE_NAME: $CI_REGISTRY/$CI_PROJECT_PATH:${CI_BUILD_REF}-alpine
    CONTAINER_IMAGE_RELEASE_NAME: $CI_REGISTRY/$CI_PROJECT_PATH:latest-alpine
