# Rationale:
#   - Build only master and tags
#   - Master is the most current not yet released state
#   - Tags are the only mean to release a version
#   - If tag matches the latest version configured here, the floating tag
#     `:latest` will be conferred to this particular image.
#   - PR are being built and tested, but not published
#   - Concurrency is disabled; Newer jobs superseding older ones
#   - To share image between stages the intermediate product will be taged with
#     `:ci-$variant` and pushed to docker hub
sudo: false
dist: trusty
language: bash
services:
  - docker

branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

env:
  - VARIANT=php70 LATEST=0.8.0

before_script:
  - env | sort
  - image="claranet/spryker-base"
  - tag="${TRAVIS_BRANCH:-${TRAVIS_TAG}}${VARIANT:+-$VARIANT}"
  - tagci="ci${VARIANT:+-$VARIANT}"

jobs:
  include:
    - stage: Build
      script:
        - docker build -t $image:$tagci .
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        - docker push $image:$tagci
    - stage: Test
      script:
      - docker run --rm -t $image:$tagci /entrypoint.sh build-base
    - stage: Publish
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then exit 0; fi'
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        - docker pull $image:$tagci
        - docker tag $image:$tagci $image:$tag;
        - docker push $image:$tag
        - if [ "$TRAVIS_TAG" == "$LATEST" ]; then
            docker tag $image:$tag $image:latest;
            docker push $image:latest;
          fi
