sudo: false
language: bash
services:
  - docker

env:
  - VERSION=0.3.5 VARIANT=php70 LATEST=yes

before_script:
  - env | sort
  - image="claranet/spryker-base"
  - tag="${VERSION}${VARIANT:+-$VARIANT}"

script:
  - docker build -t $image:$tag .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push $image:$tag;
    fi
