--- 

version: '3'
services: 

  shared-assets:
    image: "busybox:latest"
    command: /bin/true
    restart: "no"
    volumes:
      - /data/shop/public/Yves/assets
      - /data/shop/public/Zed/assets
      - /data/shop/src/Generated

  yves_and_zed: 
    image: "spryker-demoshop:latest"
    command: "run_yves_and_zed"
    restart: always
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "2381:80"
    links:
      - redis
      - elasticsearch
      - database
    env_file: ./docker-compose.env
    volumes_from:
      - shared-assets:rw

  init:
    image: "spryker-demoshop:latest"
    command: "init_setup"
    #command: sleep 1d
    restart: "no"
    privileged: true
    depends_on:
      - zed
    links:
      - redis
      - elasticsearch
      - database
    env_file: ./docker-compose.env
    volumes:
      - ../assets:/data/shop/assets
    volumes_from:
      - shared-assets:rw

  redis:
    image: "redis"
    restart: always

  elasticsearch:
    image: "elasticsearch:2"
    restart: always

  database:
    image: "postgres:9.4.10"
    restart: always
    env_file: ./docker-compose.env

  jenkins:
    image: "jenkins"
    ports: 
      - "10007:8080"
    env_file: ./docker-compose.env
    volumes:
      - /var/jenkins_home jenkins
